relaychain:
  image: parity/polkadot:v0.9.31
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
    hrmp:
      preopenHrmpChannels:
        - sender: 2000
          recipient: 2001
          maxCapacity: 8
          maxMessageSize: 102400
        - sender: 2001
          recipient: 2000
          maxCapacity: 8
          maxMessageSize: 102400
        - sender: 2000
          recipient: 2102
          maxCapacity: 8
          maxMessageSize: 102400
        - sender: 2102
          recipient: 2000
          maxCapacity: 8
          maxMessageSize: 102400
        - sender: 2001
          recipient: 2102
          maxCapacity: 8
          maxMessageSize: 102400
        - sender: 2102
          recipient: 2001
          maxCapacity: 8
          maxMessageSize: 102400

  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
  - image: acala/karura-node:2.11.0
    chain:
      base: karura-local
      collators:
        - alice
        - bob
        - charlie
      sudo: alice
    id: 2000
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    volumePath: /acala/data
    nodes:
      - wsPort: 9999
      - flags:
          - --alice
  - image: bifrostnetwork/bifrost:bifrost-v0.9.70
    chain:
      base: bifrost-local
      sudo: alice
    id: 2001
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    volumePath: /data
    nodes:
      - wsPort: 9995
      - flags:
          - --bob
  - image: kylinnetworks/kylin-collator:ro-v0.9.30
    chain: # this could be a string like `dev` or a config object
      base: pichiu-local # the chain to use
      sudo: alice
    id: 2102
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    volumePath: /data
    nodes:
      - wsPort: 9991
        rpcPort: 8833
        port: 40336
      - flags:
          - --alice
      - flags:
          - --bob
